[package]
name = "nom-kconfig"
version = "0.1.0"
edition = "2021"
authors = ["yann Prono"]
repository = "https://github.com/Mcdostone/nom-kconfig"
homepage = "https://github.com/Mcdostone/nom-kconfig"
license = "MIT"
readme = "README.md"
description = "A Kconfig parser"
categories = ["parsing"]
keywords = ["parser",  "parsing", "kconfig", "linux-kernel"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
nom_locate = "4.1.0"
regex = "1.8.4"
serde = { version = "1.0.163", features = ["derive"] }

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "my_benchmark"
harness = false

[features]
#default = ["display"]
display = []