<<<<<<< HEAD
<<<<<<< HEAD
name: Benchmark

=======
>>>>>>> 9df32bf (ci: github workflow for benchmark)
=======
name: Benchmark

>>>>>>> aafde45 (refactor: Update dependencies, github workflow for benchmark)
on:
  pull_request:
    branches: 
      - main

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> aafde45 (refactor: Update dependencies, github workflow for benchmark)
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"

<<<<<<< HEAD
=======
>>>>>>> 9df32bf (ci: github workflow for benchmark)
=======
>>>>>>> aafde45 (refactor: Update dependencies, github workflow for benchmark)
jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: default
          override: true
      - uses: Swatinem/rust-cache@v2
      - uses: boa-dev/criterion-compare-action@v3
        with:
          benchName: my_benchmark
          branchName: main
          token: ${{ secrets.GITHUB_TOKEN }}