name: Build

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y curl
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features --locked --release --all

  unit-tests:
    needs: check
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y curl
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --locked --release --all

  clippy:
    needs: check
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y curl
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- --deny warnings

  fmt:
    needs: check
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y curl
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  code-coverage:
    needs: unit-tests
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y curl
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: 0.26.1
          args: --all-features --out Xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  doc:
    needs: check
    name: documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y curl
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Build
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --document-private-items --verbose
