name: Build

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"

jobs:
  test-linux:
    name: Tests on ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y curl
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --locked --release --all

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y curl
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- --deny warnings

  fmt:
    name: Cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y curl
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  code-coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y curl
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - run: cargo install tarpaulin
      - uses: actions-rs/cargo@v1
        with:
          command: tarpaulin
          args: --all-features --out Xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}