name: Build

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"

jobs:
  test-linux:
    name: Tests on ubuntu
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.4.0
      - run: cargo test --locked --release --all

  clippy:
    name: Run Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: cargo clippy --all-targets -- --deny warnings

  fmt:
    name: Run cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: cargo fmt --all -- --check