name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main

jobs:
  dry-run-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Make sure crate is ready
        run: cargo publish --dry-run
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish the crate
        run: cargo publish --token ${CRATES_TOKEN}