name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: new version to release

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-release
        run: cargo install cargo-release
      - name: Configure git
        run: |
          git config --global user.name "Boat"
          git config --global user.email "boat@users.noreply.github.com"
      - name: Release new version
        run: cargo-release release -v "${{ github.event.inputs.version }}" --no-publish --no-confirm --execute
